### ISSUE TITLE
Please update axios to fix CSRF vul

### ISSUE THREAD

**Issue by hawaioo** [flipt-io/flipt-node#33]
Axios updated their versions to 1.6.0 to fix the problem, see https://github.com/axios/axios/issues/6022

**Comment by markphelps** [comment]
Hi @hawaioo thanks for the issue! We currently use a tool (https://buildwithfern.com/) to generate this SDK, so we are somewhat at the mercy of what they generate for the package.json / dependencies.

That said, I've asked @dsinghvi for his recommendation here

**Comment by hawaioo** [comment]
Hi @markphelps, according to this Issue https://github.com/fern-api/fern-typescript/issues/627 
SDKs generated using the latest release of https://github.com/fern-api/fern-typescript/releases/tag/0.9.0-rc1 should fix the xsrf vul. 
Would you mind considering a version bump on your end? Your cooperation in this matter would be greatly appreciated. Thank you!

**Comment by markphelps** [comment]
@hawaioo #38 swaps out axios for node-fetch

please take a look, mostly at https://github.com/flipt-io/flipt-node/pull/38/files#diff-44db24fb92214331d3845e557c568eef257639cffaea46901778da833209ef3a and let me know if you think this will cause any issues on your end

**Comment by hawaioo** [comment]
> @hawaioo #38 swaps out axios for node-fetch
> 
> please take a look, mostly at https://github.com/flipt-io/flipt-node/pull/38/files#diff-44db24fb92214331d3845e557c568eef257639cffaea46901778da833209ef3a and let me know if you think this will cause any issues on your end

LGTM, switching from axios to fetch/node-fetch should not cause any issue.

**Comment by markphelps** [comment]
@hawaioo 0.2.16 is now out with this fix! lmk how this works for you and thanks for bringing up this issue and for the review!
