### ISSUE TITLE
Trailing slash handling causes error "invalid field key: must not be empty"

### ISSUE THREAD

**Issue by R0hitYadav** [flipt-io/flipt-node#4]
It seems that attempting to list flags (v0.2.2 and v0.2.3), the trailing slash in the request url causes the api to error out with:

```
{
"code": 3,
"message": "invalid field key: must not be empty",
"details": []
}
```

https://github.com/flipt-io/flipt-node/blob/1522bcc1bf02ad2bfffddfd866e0af3998a578f4/src/api/resources/flags/client/Client.ts#L40

**Comment by dsinghvi** [comment]
@markphelps thanks for the report -- will get back to you when fixed

**Comment by zachkirsch** [comment]
PR here to upgrade fern + the TS generator to the latest versions: https://github.com/flipt-io/flipt-api/pull/69. This includes the fix for not generating trailing slashes!

**Comment by markphelps** [comment]
@R0hitYadav this should be fixed now in the latest release https://www.npmjs.com/package/@flipt-io/flipt

sorry for the inconvenience, please let us know if that fixes the issue

**Comment by R0hitYadav** [comment]
@markphelps @dsinghvi @zachkirsch Thanks for creating Flipt, I recently migrated from Unleash and I've been enjoying Flipt a lot. Can confirm that the issue's fixed now, thanks again for the exceptional response time.
